title: Tzrlk
description: The personal page of Peter Cummuskey
timezone: 'Pacific/Auckland'

include:
  - .travis.yml
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
keep_files:
  - .git
  - CNAME

gems:
  - jekyll-asciidoc
  - asciidoctor-diagram

asciidoc:
  processor: asciidoctor

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    idseparator: _
    source-highlighter: coderay
    icons: font
    imagesdir: /img

defaults:

  - scope:
      path: ''
    values:
      layout: 'default'
      page-liquid: true
      author: 'Peter Cummuskey'

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      root: ../../../
