title: Tzrlk
description: The personal page of Peter Cummuskey
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
include:
  - .travis.yml
keep_files:
  - .git
  - CNAME
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
gems:
  - jekyll-asciidoc
timezone: 'Pacific/Auckland'
defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      page-liquid: true
      author: 'Peter Cummuskey'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      root: ../../../
