= Tzrlk
:showtitle:
:page-liquid:
:page-title: Tzrlk
:page-description: My personal site

== About

== Contact
[cols=">s,<",frame="none",grid="none",options="compact"]
|========================================================================
| Email    | peterc@aetheric.co.nz
| Reddit   | http://reddit.com/u/tzrlk[/u/tzrlk]
| Google+  | http://plus.google.com/+PeterCummuskey[+PeterCummuskey]
| LinkedIn | https://nz.linkedin.com/in/petercummuskey[/in/petercummuskey]
| Twitter  | http://twitter.com/tzrlk[@Tzrlk]
|========================================================================

++++
<script type="application/ld+json">
{
	"@context": "http://schema.org/",
	"@type": "Person",
	"name": "Peter Cummuskey",
	"additionalName": "Tzrlk",
	"affiliation": [
		{
			"@type": "Organization",
			"name": "Aetheric Engineering",
			"url": "https://aetheric.co.nz/",
			"brand": {
				"@type": "Brand",
				"logo": "https://aetheric.co.nz/favicon.ico"
			}
		}
	],
	"alumniOf": {
		"@type": "EducationalOrganization",
		"name": "AUT University"
	},
	"birthDate": "29/03/1988",
	"birthPlace": {
		"@type": "Place",
		"name": "Auckland"
	},
	"email": "peterc@aetheric.co.nz",
	"familyName": "Cummuskey",
	"gender": {
		"@type": "GenderType",
		"name": "Male",
		"url": "http://schema.org/Male"
	},
	"givenName": "Peter",
	"honorificPrefix": "Rev.",
	"jobTitle": "Software Engineer",
	"memberOf": [
		{
			"@type": "Organization",
			"name": "IITP"
		}
	],
	"nationality": {
		"@type": "Country",
		"name": "New Zealand"
	},
	"parent": [
		{
			"@type": "Person",
			"name": "Grant Cummuskey"
		},
		{
			"@type": "Person",
			"name": "Renate Cummuskey"
		}
	],
	"sibling": [
		{
			"@type": "Person",
			"name": "Patrick Cummuskey",
			"url": "http://patrickcummuskey.co.nz/"
		}
	],
	"worksFor": [
		{
			"@type": "Organization",
			"name": "Bravura Solutions",
			"url": "https://bravurasolutions.com/"
		}
	]
}
</script>
++++
